server:
  port: 8082
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 110317
  appSecret: d40f0cf5-70b4-40c9-93a1-4a9ec0484836
  timeOut: 3
  codeLength: 6