server:
  port: 8082
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 110315
  appSecret: b7001340-ea81-4488-8d4d-5ba54a24f1da
  timeOut: 10
  codeLength: 6